import { PitchSlide } from '@/types';

export const pitchSlides: PitchSlide[] = [
  {
    id: 'title',
    component: 'TitleSlide',
    title: 'Evera Protocol',
    order: 1,
    backgroundColor: '#313638',
    category: 'problem',
  },
  {
    id: 'problem-1',
    component: 'ProblemSlide',
    title: 'The Misinformation Crisis',
    order: 2,
    backgroundColor: '#EF6461',
    category: 'problem',
  },
  {
    id: 'problem-2',
    component: 'StatSlide',
    title: 'The Cost of Fake News',
    order: 3,
    backgroundColor: '#313638',
    category: 'problem',
  },
  {
    id: 'solution-overview',
    component: 'SolutionSlide',
    title: 'Decentralized Truth',
    order: 4,
    backgroundColor: '#E4B363',
    category: 'solution',
  },
  {
    id: 'how-it-works',
    component: 'ArchitectureSlide',
    title: 'How Evera Works',
    order: 5,
    backgroundImage: '/images/pitch/architecture.svg',
    category: 'solution',
  },
  {
    id: 'market-size',
    component: 'MarketSlide',
    title: 'Market Opportunity',
    order: 6,
    backgroundColor: '#E0DFD5',
    category: 'market',
  },
  {
    id: 'product-features',
    component: 'FeaturesSlide',
    title: 'Core Features',
    order: 7,
    backgroundColor: '#313638',
    category: 'product',
  },
  {
    id: 'use-cases',
    component: 'UseCasesSlide',
    title: 'Real-World Applications',
    order: 8,
    backgroundColor: '#E4B363',
    category: 'product',
  },
  {
    id: 'business-model',
    component: 'BusinessModelSlide',
    title: 'Revenue Streams',
    order: 9,
    backgroundColor: '#313638',
    category: 'business',
  },
  {
    id: 'competitive-advantage',
    component: 'CompetitiveSlide',
    title: 'Why Evera Wins',
    order: 10,
    backgroundColor: '#E0DFD5',
    category: 'business',
  },
  {
    id: 'token-economics',
    component: 'TokenomicsSlide',
    title: 'Token Economics',
    order: 11,
    backgroundColor: '#313638',
    category: 'token',
  },
  {
    id: 'roadmap',
    component: 'RoadmapSlide',
    title: 'Product Roadmap',
    order: 12,
    backgroundColor: '#E4B363',
    category: 'business',
  },
  {
    id: 'team',
    component: 'TeamSlide',
    title: 'The Team',
    order: 13,
    backgroundColor: '#313638',
    category: 'team',
  },
  {
    id: 'advisors',
    component: 'AdvisorsSlide',
    title: 'Advisory Board',
    order: 14,
    backgroundColor: '#E0DFD5',
    category: 'team',
  },
  {
    id: 'traction',
    component: 'TractionSlide',
    title: 'Early Traction',
    order: 15,
    backgroundColor: '#313638',
    category: 'business',
  },
  {
    id: 'partnerships',
    component: 'PartnershipsSlide',
    title: 'Strategic Partnerships',
    order: 16,
    backgroundColor: '#E4B363',
    category: 'business',
  },
  {
    id: 'investment-opportunity',
    component: 'InvestmentSlide',
    title: 'Investment Opportunity',
    order: 17,
    backgroundColor: '#EF6461',
    category: 'investment',
  },
  {
    id: 'use-of-funds',
    component: 'UseOfFundsSlide',
    title: 'Use of Funds',
    order: 18,
    backgroundColor: '#313638',
    category: 'investment',
  },
  {
    id: 'milestones',
    component: 'MilestonesSlide',
    title: 'Key Milestones',
    order: 19,
    backgroundColor: '#E0DFD5',
    category: 'investment',
  },
  {
    id: 'vision',
    component: 'VisionSlide',
    title: 'Our Vision',
    order: 20,
    backgroundColor: '#313638',
    category: 'investment',
  },
  {
    id: 'call-to-action',
    component: 'CTASlide',
    title: 'Join the Revolution',
    order: 21,
    backgroundColor: '#E4B363',
    category: 'investment',
  },
  {
    id: 'contact',
    component: 'ContactSlide',
    title: 'Get in Touch',
    order: 22,
    backgroundColor: '#313638',
    category: 'investment',
  },
  {
    id: 'thank-you',
    component: 'ThankYouSlide',
    title: 'Thank You',
    order: 23,
    backgroundColor: '#E4B363',
    category: 'investment',
  },
];
