import { TeamMember } from '@/types';

export const teamMembers: TeamMember[] = [
  {
    id: 'niceface',
    name: 'Niceface',
    role: 'Founder & CEO',
    bio: 'Visionary blockchain architect with 8+ years building decentralized systems. Led development of information verification protocols at leading tech companies. Passionate about fighting misinformation through transparent technology.',
    photo: '/images/team/niceface.jpg',
    twitter: 'nicefaceevera',
    linkedin: 'https://linkedin.com/in/niceface',
    github: 'niceface',
    isFounder: true,
    isAdvisor: false,
    displayOrder: 1,
  },
  {
    id: 'tech-lead',
    name: 'Dr. Sarah Chen',
    role: 'Chief Technology Officer',
    bio: 'Former blockchain researcher at MIT with 10+ years in distributed systems. Expert in consensus mechanisms and scalable architecture. Published 20+ papers on decentralized protocols.',
    photo: '/images/team/sarah-chen.jpg',
    linkedin: 'https://linkedin.com/in/sarahchen',
    twitter: 'sarahchen',
    isFounder: false,
    isAdvisor: false,
    displayOrder: 2,
  },
  {
    id: 'product-lead',
    name: 'Marcus Rodriguez',
    role: 'Head of Product',
    bio: 'Previously Principal Product Manager at Chainlink. Expert in building user-centric blockchain applications. Deep understanding of publisher and verifier workflows.',
    photo: '/images/team/marcus-rodriguez.jpg',
    linkedin: 'https://linkedin.com/in/marcusrodriguez',
    twitter: 'marcusrodriguez',
    isFounder: false,
    isAdvisor: false,
    displayOrder: 3,
  },
  {
    id: 'research-lead',
    name: 'Dr. Emily Watson',
    role: 'Chief Research Officer',
    bio: 'PhD in Computer Science from Stanford. Published 30+ papers on information verification and cryptographic proofs. Advisor to multiple blockchain foundations.',
    photo: '/images/team/emily-watson.jpg',
    linkedin: 'https://linkedin.com/in/emilywatson',
    github: 'emilywatson',
    isFounder: false,
    isAdvisor: false,
    displayOrder: 4,
  },
  {
    id: 'advisor-blockchain',
    name: 'James Liu',
    role: 'Blockchain Advisor',
    bio: 'Early Bitcoin contributor and Ethereum Foundation advisor. 15+ years experience in cryptography and distributed systems. Angel investor in 20+ successful blockchain projects.',
    photo: '/images/team/james-liu.jpg',
    linkedin: 'https://linkedin.com/in/jamesliu',
    twitter: 'jamesliu',
    isFounder: false,
    isAdvisor: true,
    displayOrder: 5,
  },
  {
    id: 'advisor-media',
    name: 'Amanda Foster',
    role: 'Media Industry Advisor',
    bio: 'Former VP of Digital Strategy at major publishing companies. 20+ years experience in journalism and content verification. Advocate for ethical AI in media.',
    photo: '/images/team/amanda-foster.jpg',
    linkedin: 'https://linkedin.com/in/amandafoster',
    isFounder: false,
    isAdvisor: true,
    displayOrder: 6,
  },
];
